"""ia_models

Revision ID: 5cd78c473569
Revises: 337aad9ff426
Create Date: 2025-10-05 03:51:00.375285
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cd78c473569'
down_revision: Union[str, None] = '337aad9ff426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'ia_documents',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('str_title', sa.String(length=255), nullable=False),
        sa.Column('str_filename', sa.String(length=255), nullable=True),
        sa.Column('txt_content', sa.Text(), nullable=False),
        sa.Column('str_content_type', sa.String(length=100), nullable=True),
        sa.Column('json_metadata', sa.Text(), nullable=True),
        sa.Column(
            'str_status',
            sa.String(length=20),
            server_default=sa.text("'active'"),
            nullable=False,
        ),
        sa.Column(
            'dt_uploaded_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column(
            'dt_processed_at', sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column('int_size_bytes', sa.Integer(), nullable=True),
        sa.Column('str_content_hash', sa.String(length=64), nullable=True),
        sa.Column('audit_user_ip', sa.String(length=16), nullable=False),
        sa.Column(
            'audit_created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column(
            'audit_updated_on',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column('audit_user_login', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'ia_conversations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('str_title', sa.String(length=255), nullable=False),
        sa.Column('str_description', sa.Text(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column(
            'dt_started_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column(
            'dt_last_message_at', sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column(
            'str_status',
            sa.String(length=20),
            server_default=sa.text("'active'"),
            nullable=False,
        ),
        sa.Column('audit_user_ip', sa.String(length=16), nullable=False),
        sa.Column(
            'audit_created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column(
            'audit_updated_on',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column('audit_user_login', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'ia_messages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('txt_content', sa.Text(), nullable=False),
        sa.Column('str_role', sa.String(length=20), nullable=False),
        sa.Column('conversation_id', sa.Integer(), nullable=False),
        sa.Column(
            'dt_created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column('json_metadata', sa.Text(), nullable=True),
        sa.Column(
            'str_status',
            sa.String(length=20),
            server_default=sa.text("'active'"),
            nullable=False,
        ),
        sa.Column('audit_user_ip', sa.String(length=16), nullable=False),
        sa.Column(
            'audit_created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column(
            'audit_updated_on',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column('audit_user_login', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ['conversation_id'],
            ['ia_conversations.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ia_messages')
    op.drop_table('ia_conversations')
    op.drop_table('ia_documents')
    # ### end Alembic commands ###
