"""create processed_data table

Revision ID: 6d421afaf99a
Revises: 00292430c7bd
Create Date: 2025-09-14 21:41:05.687661
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d421afaf99a'
down_revision: Union[str, None] = '00292430c7bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'processed_data',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('input_text', sa.String(), nullable=False),
        sa.Column('processed_result', sa.String(), nullable=True),
        sa.Column('audit_user_ip', sa.String(length=16), nullable=False),
        sa.Column(
            'audit_created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column(
            'audit_updated_on',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column('audit_user_login', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_processed_data_input_text'),
        'processed_data',
        ['input_text'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_processed_data_input_text'), table_name='processed_data'
    )
    op.drop_table('processed_data')
    # ### end Alembic commands ###
