name: CI

on:
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Install dependencies
        run: uv sync

      - name: Run tests with coverage
        run: uv run pytest --cov=apps --cov-fail-under=80
        env:
          DB_URL: sqlite:///./test.db
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          SECURITY_API_SECRET_KEY: TESTE_SECRET
          SECURITY_ALGORITHM: HS256
          SECURITY_ACCESS_TOKEN_EXPIRE_MINUTES: 30
